### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by ghost** [0intro/9hist#1]
how could you commit it such long ago. When I make a commit using git command on cmd. it will show me no commit found in on github page.appreciate if you can help

**Comment by lunatikub** [comment]
`git reset --hard origin`

**Comment by 0intro** [comment]
You can use the `--date` option of `git commit`. For example:
```
git commit --date 1990-01-01
```

**Comment by ghost** [comment]
thx in advanced. I did enter git commit --date="1990-01-01" -m "1.0" but when i open my commit record on github. it show me No commits found for "myAccountName" (using 'myEmailAddress')

**Comment by 0intro** [comment]
What is your repository URL?

**Comment by 0intro** [comment]
Looking at your profile page, I think I get what you are trying to achieve. Try:

```
GIT_COMMITTER_DATE=1990-01-01 git commit --date=1990-01-01
```

**Comment by ghost** [comment]
thank you! That fixes my problem perfectly.

**Comment by 0intro** [comment]
You're welcome.
